exp_name: &exp_name base-exp

pretrained:
  use: false
  dirpath: models
  model: "pretrained.ckpt"

model:
  n_classes: 10
  dropout: 0.3

export:
  export_path: "./outputs/export"
  export_name: "model"
  name_version: True
  input_sample_shape: [1, 1, 28, 28]

data:
  img_size: 28
  img_mean: 0.1307
  img_std: 0.3081
  root_path: "./data/"
  batch_size: 128

train:
  learning_rate: 1e-3
  n_epoch: 10
  grad_accum_steps: 1
  accelerator: cuda
  devices:
    - 0
  precision: 16-mixed
  val_check_interval: 1.0
  overfit_batches: 0
  num_sanity_val_steps: 4
  full_deterministic_mode: false
  benchmark: false
  gradient_clip_val: 1.0
  profiler:
  log_every_n_steps: 50
  detect_anomaly: false

loggers:
  experiment_name: *exp_name
  wandb:
    project: mnistops
  mlflow:
    tracking_uri: http://localhost:5000
    artifact_location: ./outputs/mlflow_artifacts
    save_dir: ./outputs/mlfolw_logs
    log_model: True
    tags: { exp_name: *exp_name }
    image_path: ./img/sample.png

artifacts:
  checkpoint:
    use: true
    dirpath: checkpoints
    filename: "{epoch:02d}-{val_MulticlassAccuracy:.4f}"
    monitor: val_MulticlassAccuracy
    mode: max
    save_top_k: 3
    every_n_epochs: 3

callbacks:
  model_summary:
    max_depth: 1

triton:
  model_name: "mnist_classifier"
  server_url: "localhost:8500"
  models_path: "triton/model_repository/mnist_classifier/1"
